# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 350)
        MainWindow.setStyleSheet("background:rgb(255, 200, 221);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(110, 240, 91, 51))
        self.btn_generate.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"color: rgb(0, 48, 73);\n"
"font-size: 14px;\n"
"font: 87 8pt \"Arial Black\";\n"
"border-radius: 10px")
        self.btn_generate.setObjectName("btn_generate")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 20, 231, 41))
        self.title.setStyleSheet("font-size: 20px;\n"
"color: rgb(0, 48, 73);\n"
"font: 87 8pt \"Arial Black\";\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"font: 87 16pt \"Arial Black\";")
        self.title.setObjectName("title")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(40, 80, 161, 41))
        self.result.setMinimumSize(QtCore.QSize(161, 41))
        self.result.setMaximumSize(QtCore.QSize(161, 16777215))
        self.result.setStyleSheet("font-size: 15px;\n"
"color: rgb(0, 48, 73);\n"
"font: 87 10pt \"Arial Black\";")
        self.result.setObjectName("result")
        self.cb_number = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_number.setGeometry(QtCore.QRect(40, 150, 181, 17))
        self.cb_number.setStyleSheet("color: rgb(0, 48, 73);\n"
"font: 87 8pt \"Arial Black\";")
        self.cb_number.setObjectName("cb_number")
        self.cb_alphabete = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_alphabete.setGeometry(QtCore.QRect(40, 180, 201, 17))
        self.cb_alphabete.setStyleSheet("color: rgb(0, 48, 73);\n"
"font: 87 8pt \"Arial Black\";")
        self.cb_alphabete.setObjectName("cb_alphabete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate.setText(_translate("MainWindow", "Згенерувати"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.cb_number.setText(_translate("MainWindow", "Використовувати числа"))
        self.cb_alphabete.setText(_translate("MainWindow", "Використовувати алфавіт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
